<a href="https://colab.research.google.com/github/Adedotun-Adepoju/Hamoye-codes/blob/master/QUIZ_C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv'
df=pd.read_csv(url)
df.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [3]:
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stab', 'stabf'],
      dtype='object')

In [4]:
# drop the stab column
df.drop(columns=['stab'],axis=1,inplace=True)
df.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [5]:
# select training and target variables
X=df.drop(columns=['stabf'])
y=df[['stabf']]

In [6]:
# split the set into train and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1,test_size=0.2)

In [7]:
# scaling the training data using standardscaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_test)

array([[ 0.59395058, -0.41273345,  1.50392381, ...,  1.1672034 ,
        -1.50732963,  1.08472557],
       [ 0.2021896 ,  0.37441634, -0.18880047, ..., -0.39566024,
         1.41465051,  1.22601069],
       [-1.079044  , -0.31374544, -0.88463426, ..., -1.43849538,
         0.65182081, -1.6821675 ],
       ...,
       [ 0.94782488, -1.66372653, -1.65391963, ...,  0.12639128,
         0.57344494,  1.31934985],
       [-1.1202346 ,  0.19397855, -0.2378051 , ...,  0.79408717,
        -1.36232268, -0.80197116],
       [-1.37764025,  1.51186671,  0.28265058, ..., -0.91749729,
         0.00295027,  1.18902334]])

In [8]:
# Random forest model
from sklearn.ensemble import RandomForestClassifier
rcf=RandomForestClassifier(random_state=1)
rcf.fit(X_train,y_train)
rcf_pred=rcf.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [9]:
# confusion matrix
from sklearn.metrics import confusion_matrix
cnf_rf=confusion_matrix(y_test,rcf_pred,labels=['unstable','stable'])
cnf_rf

array([[1233,   55],
       [  87,  625]])

In [41]:
round(accuracy_score(y_test, rcf_pred), 4)

0.929

In [11]:
# metrics
from sklearn.metrics import precision_score,recall_score,f1_score,accuracy_score
print("Accuracy score {}".format(round(accuracy_score(y_test, rcf_pred), 5)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, rcf_pred, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, rcf_pred, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, rcf_pred, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, rcf_pred, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, rcf_pred, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, rcf_pred, pos_label='unstable')))

Accuracy score 0.929
Precision score for 'stable' 0.919
Precision score for 'unstable' 0.934
Recall score for 'stable' 0.878
Recall score for 'unstable' 0.957
F1 score for 'stable' 0.898
F1 score for 'unstable' 0.946


In [12]:
# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, rcf_pred))

              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



Extra Tree

In [13]:
# Extra tree classifier model
from sklearn.ensemble import ExtraTreesClassifier
extra_tree=ExtraTreesClassifier(random_state=1)
extra_tree.fit(X_train,y_train)
extra_tree_pred=extra_tree.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [14]:
# confusion matrix
cnf_ext=confusion_matrix(y_test,extra_tree_pred,labels=['unstable','stable'])
cnf_ext

array([[1250,   38],
       [ 106,  606]])

In [53]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, extra_tree_pred), 5)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, extra_tree_pred, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, extra_tree_pred, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, extra_tree_pred, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, extra_tree_pred, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, extra_tree_pred, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, extra_tree_pred, pos_label='unstable')))

Accuracy score 0.928
Precision score for 'stable' 0.941
Precision score for 'unstable' 0.922
Recall score for 'stable' 0.851
Recall score for 'unstable' 0.97
F1 score for 'stable' 0.894
F1 score for 'unstable' 0.946


In [16]:
# Classification report
print(classification_report(y_test, extra_tree_pred))

              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



XGBOOST

In [17]:
# xgboost with random forest
from xgboost import XGBRFClassifier
xgb_model = XGBRFClassifier(random_state=1)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
# CONFUSION MATRIX
cnf_xgb = confusion_matrix(y_test, xgb_pred, labels=['unstable', 'stable'])
cnf_xgb 

array([[1209,   79],
       [ 298,  414]])

In [19]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, xgb_pred), 3)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, xgb_pred, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, xgb_pred, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, xgb_pred, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, xgb_pred, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, xgb_pred, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, xgb_pred, pos_label='unstable')))

Accuracy score 0.812
Precision score for 'stable' 0.84
Precision score for 'unstable' 0.802
Recall score for 'stable' 0.581
Recall score for 'unstable' 0.939
F1 score for 'stable' 0.687
F1 score for 'unstable' 0.865


In [20]:
# Classification report
print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

      stable       0.84      0.58      0.69       712
    unstable       0.80      0.94      0.87      1288

    accuracy                           0.81      2000
   macro avg       0.82      0.76      0.78      2000
weighted avg       0.82      0.81      0.80      2000



In [21]:
# Xgboost with gradioent boosting
from xgboost import XGBClassifier
model_xgb = XGBClassifier(random_state=1)
model_xgb.fit(X_train, y_train)
pred_xgb = model_xgb.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
# CONFUSION MATRIX
cnf_xgb = confusion_matrix(y_test, pred_xgb, labels=['unstable', 'stable'])
cnf_xgb 

array([[1236,   52],
       [ 109,  603]])

In [42]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_xgb), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_xgb, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_xgb, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_xgb, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_xgb, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_xgb, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_xgb, pos_label='unstable')))

Accuracy score 0.9195
Precision score for 'stable' 0.921
Precision score for 'unstable' 0.919
Recall score for 'stable' 0.847
Recall score for 'unstable' 0.96
F1 score for 'stable' 0.882
F1 score for 'unstable' 0.939


In [24]:
# Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, pred_xgb))

              precision    recall  f1-score   support

      stable       0.92      0.85      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



LIGHTGBM

In [25]:
# lightgbm
from lightgbm import LGBMClassifier
model_light = LGBMClassifier(random_state=1)
model_light.fit(X_train, y_train)
pred_light = model_light.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
# CONFUSION MATRIX
cnf_light = confusion_matrix(y_test, pred_light, labels=['unstable', 'stable'])
cnf_light

array([[1239,   49],
       [  76,  636]])

In [43]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, pred_light), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, pred_light, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test, pred_light, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, pred_light, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, pred_light, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, pred_light, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, pred_light, pos_label='unstable')))

Accuracy score 0.9375
Precision score for 'stable' 0.928
Precision score for 'unstable' 0.942
Recall score for 'stable' 0.893
Recall score for 'unstable' 0.962
F1 score for 'stable' 0.911
F1 score for 'unstable' 0.952


RANDOMIZED SEARCH

In [28]:
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 
hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}

In [44]:
from sklearn.model_selection import RandomizedSearchCV
rand_search=RandomizedSearchCV(extra_tree,hyperparameter_grid,random_state=1,cv=5,n_iter=10,scoring='accuracy',n_jobs=-1,verbose=1)
rand_search.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.6min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.6min finished
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:739: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                        

In [46]:
rand_search.best_params_

{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [47]:
rand_search.best_estimator_

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features=None,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=8, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=1000,
                     n_jobs=None, oob_score=False, random_state=1, verbose=0,
                     warm_start=False)

In [48]:
best_xtra=rand_search.best_estimator_
best_xtra.fit(X_train,y_train)
best_pred=best_xtra.predict(X_test)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


In [49]:
# CONFUSION MATRIX
cnf_mat_newxt = confusion_matrix(y_test, best_pred, labels=['unstable', 'stable'])
print(cnf_mat_newxt) 

[[1235   53]
 [  93  619]]


In [51]:
# metrics
print("Accuracy score {}".format(round(accuracy_score(y_test, best_pred), 4)))
print("Precision score for 'stable' {}".format(round(precision_score(y_test, best_pred, pos_label='stable'), 3)))
print("Precision score for 'unstable' {}".format(round(precision_score(y_test,best_pred, pos_label='unstable'), 3)))
print("Recall score for 'stable' {}".format(round(recall_score(y_test, best_pred, pos_label='stable'), 3)))
print("Recall score for 'unstable' {}".format(round(recall_score(y_test, best_pred, pos_label='unstable'), 3)))
print("F1 score for 'stable' %.3f" % (f1_score(y_test, best_pred, pos_label='stable')))
print("F1 score for 'unstable' %.3f" % (f1_score(y_test, best_pred, pos_label='unstable')))

Accuracy score 0.927
Precision score for 'stable' 0.921
Precision score for 'unstable' 0.93
Recall score for 'stable' 0.869
Recall score for 'unstable' 0.959
F1 score for 'stable' 0.895
F1 score for 'unstable' 0.944


In [35]:
# Classification report
print(classification_report(y_test, best_pred))

              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [36]:
best_xtra.feature_importances_

array([0.13723979, 0.14050787, 0.1346805 , 0.13541662, 0.00368361,
       0.0053368 , 0.00542927, 0.0049625 , 0.10256224, 0.1075776 ,
       0.11306257, 0.10954062])

In [37]:
# Showing features in order of importance
sorted(zip(best_xtra.feature_importances_,df.drop(columns=['stabf'],axis=1)),reverse=True)

[(0.14050787123292582, 'tau2'),
 (0.13723978831645356, 'tau1'),
 (0.13541662265504284, 'tau4'),
 (0.13468049625184006, 'tau3'),
 (0.1130625748200639, 'g3'),
 (0.10954061786399034, 'g4'),
 (0.10757760496355806, 'g2'),
 (0.10256224382786308, 'g1'),
 (0.0054292680802320815, 'p3'),
 (0.0053368014620138494, 'p2'),
 (0.004962501777389839, 'p4'),
 (0.0036836087486265406, 'p1')]

In [54]:
sorted(zip(extra_tree.feature_importances_,df.drop(columns=['stabf'],axis=1)),reverse=True)

[(0.11844468079199041, 'tau2'),
 (0.11739736493320078, 'tau1'),
 (0.11546569217199552, 'tau4'),
 (0.11316851246674982, 'tau3'),
 (0.09688268324346265, 'g3'),
 (0.09401881529815702, 'g4'),
 (0.09367635844551439, 'g2'),
 (0.08978290601483987, 'g1'),
 (0.040706278296424536, 'p3'),
 (0.040578638540044426, 'p4'),
 (0.04037131556379323, 'p2'),
 (0.039506754233827476, 'p1')]